spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/cursosapidb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: never
    job:
      enable: false

